"""
MEGA TRANSLATION SCRIPT - Space Channel 5 Part 2
Translates ALL text entries from English/Italian to Brazilian Portuguese.
Run: python tools/translate_all.py
"""
import json, sys

TRANSLATION_FILE = r"C:\Users\gorigamia\Desktop\game\translation.json"

with open(TRANSLATION_FILE, 'r', encoding='utf-8') as f:
    data = json.load(f)

count = 0

def t(file_pattern, entry_id, translated_lines):
    """Apply translation to matching files in both CVMs."""
    global count
    for key, fdata in data["files"].items():
        if file_pattern not in key:
            continue
        for entry in fdata["entries"]:
            if entry["id"] == entry_id:
                entry["translated"] = translated_lines
                count += 1

def tb(file_pattern, translations_dict):
    """Bulk apply translations: {id: [lines], ...}"""
    for eid, lines in translations_dict.items():
        t(file_pattern, eid, lines)

# ================================================================
# TITCAP_E.BIN (28 entries - Menu/Report descriptions)
# ================================================================
tb("TITCAP_E.BIN", {
    0: ["Dance numa tempestade solo.",
        "Jogue como a reporter do Canal 5, Ulala, e pare os",
        "planos diabolicos dos Rhythm Rogues!"],
    1: ["Ainda mais quente com dois!",
        "Jogador 1: Controla os botoes direcionais.",
        "Jogador 2: Controla os botoes de acao."],
    2: ["Batalha sem parar de 100 rounds.",
        "Consiga rankings maiores",
        "para ganhar novas roupas da Ulala."],
    3: ["Enfrente todos os 100 rounds com um parceiro!",
        "Jogador 1: Controla os botoes direcionais.",
        "Jogador 2: Controla os botoes de acao."],
    4: ["Veja os perfis da grande",
        "variedade de personagens",
        "*Voce tambem encontrara varias dicas sobre",
        "estrategia e comandos secretos!"],
    5: ["Troque a roupa da Ulala.",
        "Selecione suas roupas e itens favoritos",
        "encontrados ao longo do jogo!",
        "*So pode ser usado em reports concluidos."],
    6: ["Mude o ambiente de jogo.",
        "Inclui Stereo/Mono, Configuracao de Botoes,",
        "Vibracao Ligada/Desligada, Legendas Ligada/Desligada,",
        "alem de outras opcoes."],
    7: ["Ajuste o audio",
        "para stereo",
        "ou mono."],
    8: ["Ativa ou desativa a vibracao.",
        "Quando LIGADA, o controle",
        "vai vibrar."],
    9: ["Configure cada um dos botoes",
        "do seu jeito.",
        "Pressione o botao O para ir para",
        "a tela de configuracao de botoes."],
    10: ["Retorna todas as configuracoes para",
         "as configuracoes padrao.",
         "Pressione o botao O para retornar",
         "todas as configuracoes ao padrao."],
    11: ["Ative ou desative as legendas",
         "de karaoke.",
         "LIGADA (mostrar legendas)",
         "ou DESLIGADA (nao mostrar legendas)."],
    12: ["Titulo: Ulala esta de volta!",
         "Local: Sinfonia Espacial",
         "Status: Uma nave de cruzeiro sobre",
         "Neo-Plutao foi atacada por uma trupe de danca!"],
    13: ["Titulo: A Vinganca da Natureza!",
         "Local: Parque Espacial",
         "Status: O Presidente foi a uma noite de bandas,",
         "so pra ser capturado por plantas monstruosas!"],
    14: ["Titulo: Conheca a Policia Espacial Sexy!",
         "Local: A estratosfera",
         "Status: Ulala esta atras de um furo, mas",
         "a Policia Espacial nao quer nem saber!"],
    15: ["Titulo: O fim do Space Channel 5?!",
         "Local: Estudio de Transmissao Principal",
         "Status: Os Rhythm Rogues partiram para o",
         "ataque total! E Michael esta em perigo!"],
    16: ["Titulo: Os Espias se Vingam!",
         "Local: Zona Misteriosa",
         "Status: O Channel 5 parte para o ataque!",
         "Hora de uma espionagem sorrateira!"],
    17: ["Titulo: Especial de TV do Purge",
         "Local: A Arena Espacial",
         "Status: Como a Ulala vai parar o plano",
         "do Purge de fazer a galaxia dancar loucamente?!"],
    18: ["[2o Mundo]",
         "Titulo: Ulala esta de volta! De novo!",
         "Local: Sinfonia Espacial",
         "Status: Hordas de novos personagens!"],
    19: ["[2o Mundo]",
         "Titulo: A Vinganca da Natureza! De novo!",
         "Local: Parque Espacial",
         "Status: Cachorros! Cachorros! Cachorros!"],
    20: ["[2o Mundo]",
         "Titulo: Conheca a Policia Espacial Sexy! De novo!",
         "Local: A estratosfera",
         "Status: Olha, e a irmazinha do Pine!"],
    21: ["[2o Mundo]",
         "Titulo: O fim mesmo do Space Channel 5?!",
         "Local: Estudio de Transmissao Principal",
         "Status: As Lideres de Torcida assumem o controle!"],
    22: ["[2o Mundo]",
         "Titulo: Os Espias se Vingam! De novo!",
         "Local: Zona Misteriosa",
         "Status: Adivinha qual banda se reuniu!"],
    23: ["[2o Mundo]",
         "Titulo: Especial de TV do Purge (2a temporada!)",
         "Local: A Arena Espacial",
         "Status: Revanche! Ulala vs. Purge!"],
    24: ["Ajuste o volume dos dialogos",
         "de 0 (mudo) a 6 (total de 7 niveis).",
         "Use os botoes direcionais Esquerda e Direita",
         "para ajustar."],
    25: ["Ajuste o volume da musica",
         "de 0 (mudo) a 6 (total de 7 niveis).",
         "Use os botoes direcionais Esquerda e Direita",
         "para ajustar."],
    26: ["Voce pode ativar e desativar",
         "as legendas aqui."],
    27: ["Voce pode CARREGAR os dados do jogo."],
})

# ================================================================
# WARNCAPE.BIN (28 entries - Memory Card messages)
# ================================================================
tb("WARNCAPE.BIN", {
    0: ["Verificando o memory card (PS2) ou controle."],
    1: ["Nenhum memory card (PS2) inserido.",
        "Para salvar e preciso pelo menos 161KB.",
        "Se voce continuar sem um",
        "memory card (PS2), nao podera",
        "salvar. Tudo bem?"],
    2: ["Nao ha espaco livre suficiente no",
        "memory card (PS2).",
        "Para salvar e preciso pelo menos 161KB. Se voce",
        "continuar, nao podera salvar.",
        "Tudo bem?"],
    3: ["Falha ao carregar. Cancelar e continuar?"],
    4: ["O arquivo esta corrompido. Cancelar o",
        "carregamento e continuar?"],
    5: ["Carregamento completo."],
    6: ["O memory card (PS2) no",
        "SLOT 1 contem dados do jogo. Sobrescrever?",
        "(Selecionar 'Nao' vai continuar o jogo",
        "sem salvar)."],
    7: ["Salvando automaticamente. Nao remova o",
        "memory card (PS2) ou desligue o console."],
    8: ["Salvamento completo."],
    9: ["Falha ao salvar. Continuar sem salvar?"],
    10: ["Comecar do inicio da ultima area."],
    11: ["Comecar da primeira area deste",
         "report."],
    12: ["Salvar itens e personagens",
         "obtidos e sair."],
    13: ["O memory card (PS2) no",
         "SLOT 1 nao foi formatado. Formatar",
         "agora?"],
    14: ["Formatando. Nao remova o",
         "memory card (PS2) ou desligue o console."],
    15: ["Se continuar sem salvar",
         "nao podera salvar.",
         "Tudo bem?"],
    16: ["Falha na formatacao. Cancelar e",
         "continuar? (Pressionar 'Sim' vai permitir",
         "continuar mas nao sera possivel",
         "salvar.)"],
    17: ["Sim"],
    18: ["Nao"],
    19: ["Carregando dados. Nao remova o memory",
         "card (PS2) ou desligue o console."],
    20: ["O memory card (PS2) nao contem",
         "dados de Space Channel 5.2.",
         "Criar novos dados de jogo?"],
    21: ["Nenhum memory card (PS2) inserido."],
    22: ["O memory card (PS2) nao contem",
         "dados de Space Channel 5.2."],
    23: ["O memory card (PS2) no",
         "SLOT 1 nao foi formatado."],
    24: ["Carregar dados do memory card (PS2)?"],
    25: ["Tem certeza?"],
    26: ["Falha ao carregar.",
         "Pressione o botao X para continuar."],
    27: ["Salvando... Nao remova o",
         "memory card (PS2) ou desligue o console."],
})

# ================================================================
# COSCAP_E.BIN (104 entries - Costumes & Items)
# ================================================================
tb("COSCAP_E.BIN", {
    0: ["[Nome] Roupa Retro do Channel 5",
        "[Condicao] Disponivel desde o inicio",
        "Uniforme novo da empresa.",
        "Material ultra elastico pra se mexer facil."],
    1: ["[Nome] Roupa Retro do Channel 5",
        "[Condicao] Disponivel desde o inicio",
        "Uniforme novo da empresa.",
        "Material ultra elastico pra se mexer facil."],
    2: ["[Nome] ?????",
        "[Condicao] Conclua o Report 2",
        "?????"],
    3: ["[Nome] Fantasia de Flor",
        "[Condicao] Conclua o Report 2 Traje aromatico",
        "multifuncional. Regula temperatura e umidade",
        "pra reportagens mais agradaveis."],
    4: ["[Nome] ?????",
        "[Condicao] Conclua o Report 3",
        "?????"],
    5: ["[Nome] Roupa Gogo (sem capacete)",
        "[Condicao] Conclua o Report 3",
        "Projetada para proteger o corpo humano de",
        "poeira espacial em altas velocidades."],
    6: ["[Nome] Fantasia Maluca (provisorio)",
        "[Condicao] ?????",
        "?????"],
    7: ["[Nome] Roupa Gogo (com capacete)",
        "[Condicao] Conclua o Report 4",
        "Indispensavel pra qualquer cidadao espacial.",
        "O capacete pode ser guardado nas costas."],
    8: ["[Nome] Traje de Espia",
        "[Condicao] ?????",
        "?????"],
    9: ["[Nome] Traje de Espia",
        "[Condicao] Conclua o Report 5 Projetado para",
        "infiltracao. Um fio especial nas costas permite",
        "que o usuario se mova como uma aranha."],
    10: ["[Nome] Roupa Favorita Antiga (provisorio)",
         "[Condicao] ?????",
         "?????"],
    11: ["[Nome] Roupa Retro Antiga",
         "[Condicao] Conclua o Report 6",
         "A roupa que a Ulala usava no incidente",
         "Morolian. Estava guardada no armario."],
    12: ["[Nome] Traje Elegante (provisorio)",
         "[Condicao] ?????",
         "?????"],
    13: ["[Nome] Roupa Retro Antiga",
         "[Condicao] Conclua o Report 6 no 2o Mundo.",
         "Ficou toda suja quando a Ulala foi",
         "atacada. Uma reliquia de colecionador!"],
    14: ["[Nome] Traje Fabuloooso (provisorio)",
         "[Condicao] ?????",
         "?????"],
    15: ["[Nome] Super Fantasia Ulala",
         "[Condicao] Conclua o Report 6 Um super traje",
         "feito de energia de danca concentrada.",
         "Dizem que na verdade e so roupa de baixo."],
    16: ["[Nome] ?????",
         "[Condicao] Conclua 24 rodadas consecutivas no",
         "modo Danca da Ulala.",
         "?????"],
    17: ["[Nome] Uniforme Escolar",
         "[Condicao] Conclua 24 rodadas consecutivas no",
         "modo Danca da Ulala. Uma versao modificada",
         "do uniforme do Colegio M."],
    18: ["[Nome] Vestido Chines",
         "[Condicao] Conclua 100 rodadas consecutivas no",
         "modo Danca da Ulala.",
         "?????"],
    19: ["[Nome] Vestido Chines",
         "[Condicao] Conclua 100 rodadas consecutivas no",
         "modo Danca da Ulala. Usado na investigacao",
         "secreta no restaurante de Shanghai."],
    20: ["[Nome] ?????",
         "[Condicao] Conclua o Report 1 com indices de",
         "audiencia de 100%.",
         "?????"],
    21: ["[Nome] Roupa de La",
         "[Condicao] Conclua o Report 1 com indices de",
         "audiencia de 100%.",
         "Ulala usou isso num bico antigo."],
    22: ["[Nome] ?????",
         "[Condicao] Mais de 10 horas de jogo."],
    23: ["[Nome] Traje Furtivo",
         "[Condicao] Mais de 10 horas de jogo."],
    24: ["[Nome] ?????",
         "[Condicao] Conclua o Report 2 com indices de",
         "audiencia de 100%.",
         "?????"],
    25: ["[Nome] Fantasia de Pudding",
         "[Condicao] Conclua o Report 2 com indices de",
         "audiencia de 100%.",
         "Uma fantasia de Pudding."],
    26: ["[Nome] ?????",
         "[Condicao] Conclua o Report 3 com indices de",
         "audiencia de 100%.",
         "?????"],
    27: ["[Nome] Fantasia de Pine",
         "[Condicao] Conclua o Report 3 com indices de",
         "audiencia de 100%.",
         "Uma fantasia de Pine."],
    28: ["[Nome] ?????",
         "[Condicao] Conclua 34 rodadas consecutivas no",
         "modo Danca da Ulala vestindo o",
         "Traje Morolian."],
    29: ["[Nome] Traje Sincronia",
         "[Condicao] Conclua 34 rodadas consecutivas no",
         "modo Danca da Ulala vestindo o",
         "Traje Morolian."],
    30: ["[Nome] Traje Space Michael",
         "[Condicao] ?????",
         "?????"],
    31: ["[Nome] Traje Space Michael",
         "[Condicao] Conclua o Report 4 com indices de",
         "audiencia de 100%.",
         "Uma fantasia de Space Michael."],
    32: ["[Nome] Fantasia de Jaguar",
         "[Condicao] ?????",
         "?????"],
    33: ["[Nome] Fantasia de Jaguar",
         "[Condicao] Conclua o Report 5 com indices de",
         "audiencia de 100%.",
         "Uma fantasia de Jaguar."],
    34: ["[Nome] Traje Adulto (provisorio)",
         "[Condicao] ?????",
         "?????"],
    35: ["[Nome] Fantasia de Peace",
         "[Condicao] Conclua o Report 2 no 2o Mundo",
         "Uma fantasia do Presidente Peace, usada para",
         "criar uma isca. Artigo de segunda mao."],
    36: ["[Nome] ?????",
         "[Condicao] Conclua o Report 3",
         "?????"],
    37: ["[Nome] Fantasia de Noize",
         "[Condicao] Conclua o Report 3.",
         "Uma fantasia de Noize. Tem uma funcao secreta",
         "que faz quem usa parecer menor."],
    38: ["[Nome] ?????",
         "[Condicao] ????? Este traje na verdade e so",
         "pintura corporal e",
         "lentes de contato coloridas."],
    39: ["[Nome] Traje Evila (upgrade)",
         "[Condicao] Conclua o Report 4 no 2o Mundo.",
         "Este traje na verdade e so pintura corporal e",
         "lentes de contato coloridas."],
    40: ["[Nome] Roupa de Genio",
         "[Condicao] ?????",
         "?????"],
    41: ["[Nome] Traje Purge Dancante",
         "[Condicao] Conclua o Report 6 no 2o Mundo.",
         "Um traje misterioso projetado pra confundir",
         "inimigos com mini espelhos roxos de discoteca."],
    42: ["[Nome] ?????",
         "[Condicao] Salve os Astronautas",
         "Neo-Japoneses.",
         "?????"],
    43: ["[Nome] Astronauta Neo-Japones",
         "[Condicao] Salve os Astronautas",
         "Neo-Japoneses.",
         "Usado quando se infiltraram na excursao."],
    44: ["[Nome] ?????",
         "[Condicao] ?????",
         "Vista quando quiser se sentir fracote."],
    45: ["[Nome] Traje do Sr. Nervoso",
         "[Condicao] Salve o Sr. Nervoso",
         "durante o jogo.",
         "Vista quando quiser se sentir fracote."],
    46: ["[Nome] ?????",
         "[Condicao] ?????",
         "Usada na investigacao da cozinha."],
    47: ["[Nome] Traje de Chef",
         "[Condicao] Salve o Chef (verde) durante",
         "o jogo.",
         "Usada na investigacao da cozinha."],
    48: ["[Nome] ?????",
         "[Condicao] ?????",
         "Usada na investigacao secreta do",
         "cursinho clandestino."],
    49: ["[Nome] Traje do Ensino Fundamental",
         "[Condicao] Salve o Quarteto da Banda do Ensino",
         "Fundamental durante o jogo. Usada na investigacao",
         "do cursinho clandestino."],
    50: ["[Nome] ?????",
         "[Condicao] ?????",
         "Pra quando quiser se sentir machao."],
    51: ["[Nome] Traje da Equipe de Resgate",
         "[Condicao] Salve a Equipe de Resgate",
         "durante o jogo.",
         "Pra quando quiser se sentir machao."],
    52: ["[Nome] ?????",
         "[Condicao] Salve a Vovozinha Espacial",
         "durante o jogo.",
         "?????"],
    53: ["[Nome] Traje de Vovozinha",
         "[Condicao] Salve a Vovozinha Espacial",
         "durante o jogo. Usada na infiltracao secreta",
         "no esconderijo dos Bandidos Geriatricos."],
    54: ["[Nome] ?????",
         "[Condicao] Mais de 10 horas de jogo.",
         "Um traje especial com informacoes sobre",
         "comandos secretos escritas por dentro."],
    55: ["[Nome] Traje em Branco",
         "Pressione \u2557, \u255d & \u00a2 segurando L1 e",
         "R1 para ativar o Modo Invencivel.",
         "Pressione de novo para cancelar."],
    56: ["[Nome] ?????",
         "[Condicao] Mais de 20 horas de jogo.",
         "?????"],
    57: ["[Nome] Traje Sexy Hardcore",
         "[Condicao] Mais de 20 horas de jogo.",
         "Uma roupa ousada como poucas.",
         "Voce pode virar uma pin-up!"],
    58: ["[Nome] ?????",
         "[Condicao] Conclua 7 rodadas consecutivas no",
         "modo Danca da Ulala",
         "vestindo o Traje Morolian."],
    59: ["[Nome] Traje de Robo (prata)",
         "[Condicao] Conclua 7 rodadas consecutivas no",
         "modo Danca da Ulala",
         "vestindo o Traje Morolian."],
    60: ["[Nome] ?????",
         "[Condicao] Conclua 14 rodadas consecutivas no",
         "modo Danca da Ulala",
         "vestindo o Traje Morolian."],
    61: ["[Nome] Traje Robo (Machao)",
         "[Condicao] Conclua 14 rodadas consecutivas no",
         "modo Danca da Ulala",
         "vestindo o Traje Morolian."],
    62: ["[Nome] Traje Morolian",
         "[Condicao] Conclua o report final.",
         "?????"],
    63: ["[Nome] Traje Morolian",
         "[Condicao] Conclua o Report 6",
         "Algo vai acontecer se voce jogar o modo",
         "Danca da Ulala vestindo este traje."],
    64: ["[Nome] Traje Chefe Morolian",
         "[Condicao] ?????",
         "?????"],
    65: ["[Nome] Traje Chefe Morolian",
         "[Condicao] Conclua todos os reports",
         "(1-6) com indices de audiencia de 100%.",
         "Fantasia do Chefe Morolian."],
    66: ["[Nome] Traje Menor (provisorio)",
         "[Condicao] ?????",
         "?????"],
    67: ["[Nome] Traje do Homem Oitenta e Oito",
         "[Condicao] Conclua o Report 3 no 2o Mundo.",
         "Usado pra se infiltrar nos estudios do Channel 88",
         "e reportar o escandalo que rolou la."],
    68: ["[Nome] ?????",
         "[Condicao] Conclua todas as 100 rodadas no modo",
         "Danca da Ulala vestindo o",
         "Traje Morolian."],
    69: ["[Nome] Fantasia do Purge Encapuzado",
         "[Condicao] Conclua todas as 100 rodadas no modo",
         "Danca da Ulala vestindo o",
         "Traje Morolian."],
    70: ["[Nome] ?????",
         "[Condicao] Conclua o Report 1 em modo 2 jogadores",
         "?????"],
    71: ["[Nome] Traje Listrado",
         "[Condicao] Conclua o Report 1 em modo 2 jogadores",
         "Uma amostra recebida do dono da loja.",
         "A Ulala fez umas melhorias por conta propria."],
    72: ["[Nome] ?????",
         "[Condicao] Conclua o Report 2 em modo 2 jogadores",
         "?????"],
    73: ["[Nome] Fantasia Camuflada",
         "[Condicao] Conclua o Report 2 em modo 2 jogadores",
         "Usada pra se infiltrar na fabrica maligna",
         "de gengibre Crimson Cosmos."],
    74: ["[Nome] ?????",
         "[Condicao] Mais de 30 horas de jogo.",
         "?????"],
    75: ["[Nome] Roupa Preta",
         "[Condicao] Mais de 30 horas de jogo.",
         "Usada pra se infiltrar na oficina de couro. Feita",
         "as pressas, entao as cores desbotam facil."],
    76: ["[Nome] ?????",
         "[Condicao] Conclua 53 rodadas consecutivas no",
         "modo Danca da Ulala em 2 jogadores.",
         "?????"],
    77: ["[Nome] Traje Pessego",
         "[Condicao] Conclua 53 rodadas consecutivas no",
         "modo Danca da Ulala em 2 jogadores.",
         "Roupa pessoal da Ulala pra ir as compras."],
    78: ["[Nome] ?????",
         "[Condicao] Conclua XX numero de",
         "rodadas consecutivas no modo Danca da Ulala.",
         "?????"],
    79: ["[Nome] Fantasia Ulala Coco",
         "[Condicao] Conclua 53 rodadas consecutivas no",
         "modo Danca da Ulala.",
         "Nao e um traje de verdade -- e so um bronzeado!"],
    80: ["[Nome] Microfone da Ulala",
         "[Condicao] Disponivel desde o inicio.",
         "Microfone novo da empresa.",
         "A Ulala pintou de azul sem pedir permissao."],
    81: ["[Nome] Microfone da Ulala",
         "[Condicao] Disponivel desde o inicio",
         "Microfone novo da empresa.",
         "A Ulala pintou de azul sem pedir permissao."],
    82: ["[Nome] ?????",
         "[Condicao] ?????",
         "????"],
    83: ["[Nome] Rei das Frigideiras",
         "[Condicao] Presente do Chef (verde).",
         "Prova a vitoria dele no 255o Concurso Anual de",
         "Culinaria Espacial. Alta conducao de calor."],
    84: ["[Nome] ?????",
         "[Condicao] ?????",
         "?????"],
    85: ["[Nome] Sorvete",
         "[Condicao] Projetado por Noize. Feito",
         "para a investigacao secreta do",
         "shopping (vem com camera escondida)."],
    86: ["[Nome] ?????",
         "[Condicao] ?????",
         "?????"],
    87: ["[Nome] Batedor de Ovos Lendario",
         "[Condicao] Presente do Chef (agua-marinha) Feito",
         "de um metal ??? extraido de ruinas antigas.",
         "Otimo para bater creme caseiro!"],
    88: ["[Nome] ?????",
         "[Condicao] ?????",
         "?????"],
    89: ["[Nome] Pirulito",
         "[Condicao] Presente dos alunos da banda.",
         "Um pouco pegajoso.",
         "(Pre-lambido)"],
    90: ["[Nome] ?????",
         "[Condicao] ?????",
         "?????"],
    91: ["[Nome] Lanterna.",
         "[Condicao] Dado por um Astronauta Neo-Japones.",
         "Souvenir da Vila Edo na Cidade do Sol.",
         "Uma luminaria eficiente feita de papel de arroz."],
    92: ["[Nome] ?????",
         "[Condicao] ?????",
         "?????"],
    93: ["[Nome] Super Concha",
         "[Condicao] Presente do Chef (amarelo).",
         "Utensilio com dureza de mais de 8 bilhoes de",
         "die. So existem outras duas em toda a galaxia."],
    94: ["[Nome] ?????",
         "[Condicao] ?????",
         "?????"],
    95: ["[Nome] Canecao",
         "[Condicao] Presente da Equipe de Resgate.",
         "Perfeito pra Ginger Ales da Via Lactea.",
         "Inclui um dispositivo de resfriamento semi-natural."],
    96: ["[Nome] ?????",
         "[Condicao] ?????",
         "?????"],
    97: ["[Nome] Leque Dobravel",
         "[Condicao] Presente do Diretor Nervoso.",
         "Leque favorito da mae do Diretor Nervoso.",
         "Cria um aroma agradavel quando abanado."],
    98: ["[Nome] ?????",
         "[Condicao] ?????",
         "?????"],
    99: ["[Nome] Rosa Carmesim",
         "[Condicao] Presente do Jaguar",
         "Cheia da paixao do Jaguar, esta rosa",
         "nunca vai morrer."],
    100: ["[Nome] ?????",
          "[Condicao] ?????",
          "?????"],
    101: ["[Nome] Espiga de Milho",
          "[Condicao] Projetado por Noize. Microfone usado",
          "na reportagem secreta da mega fazenda.",
          "Usado pra baixar a guarda dos oponentes."],
    102: ["[Nome] ?????",
          "[Condicao] ?????",
          "?????"],
    103: ["[Nome] Cebolinha Verde",
          "[Condicao] Presente da Pine.",
          "100% natural, colhida de um jardim de verdade.",
          "Delicia absoluta quando cozinhada direito."],
})

# ================================================================
# R01CAP_E.BIN (29 entries - Ulala's Dance mode)
# ================================================================
tb("R01CAP_E.BIN", {
    0: ["Atingiu o Nivel 10 de Groove"],
    1: ["Atingiu o Nivel 4 de Groove"],
    2: ["Atingiu o Nivel 1 de Groove"],
    3: ["Voce agora e um Groovemaster 2000"],
    4: ["Seu Groove agora e Insano"],
    5: ["Voce ganhou o titulo de General Groove"],
    6: ["Voce e adorado como o Guru do Groove mundial"],
    7: ["Agora voce e o Guru do Groove Insano"],
    8: ["Retornou ao status original"],
    9: ["Pressione o botao X quando ouvir WOOF"],
    10: ["Pressione o botao X quando ouvir MEOW"],
    11: ["Pressione o botao X quando ouvir TOYOTA"],
    12: ["Pressione o botao O quando ouvir HONDA"],
    13: ["Pressione o botao X quando ouvir WOOF"],
    14: ["Pressione o botao X quando ouvir MEOW"],
    15: ["Pressione o botao X quando ouvir TOYOTA"],
    16: ["Pressione o botao O quando ouvir HONDA"],
    17: ["Para sair da Danca da Ulala",
         "Pressione o botao START e escolha salvar e sair"],
    18: ["Demais!"],
    19: ["Perfeito!"],
    20: ["Nv. 10 Groove"],
    21: ["Nv. 4 Groove"],
    22: ["Groovemaster 2000"],
    23: ["Groove Insano"],
    24: ["Guru do Groove"],
    25: ["Guru do Groove Insano"],
    26: ["Nv. 1 Groove"],
    27: ["Mova a camera com",
         "o analogico esquerdo!"],
    28: ["Nivel 00"],
})

# ================================================================
# R10CAP_E.BIN (3 entries - Report 1 intro)
# ================================================================
tb("R10CAP_E.BIN", {
    0: ["Nave de Cruzeiro Espacial",
        "\"Sinfonia Cosmica\""],
    1: ["Nave de Transmissao Movel do Channel 5",
        "\"Astrobeat\""],
    2: ["Ulala esta de volta!"],
})

# ================================================================
# R11CAP_E.BIN (35 entries - Report 1 Part 1)
# ================================================================
tb("R11CAP_E.BIN", {
    0: ["Flash de Noticias"],
    1: ["Se os coracoes acabarem, o resgate falha!"],
    2: ["Memorize os movimentos!"],
    3: ["Pressione os botoes!"],
    4: ["Pressione o botao X quando ouvir CHU"],
    5: ["Pressione o botao X quando ouvir CHU"],
    6: ["Botao X--"],
    7: ["Botao X--"],
    8: ["Use o raio do botao X para CHU"],
    9: ["Use o raio do botao X para CHU"],
    10: ["Esquerda e ESQUERDA, Direita e DIREITA"],
    11: ["Pressione o botao O quando ouvir HEY"],
    12: ["Pressione o botao O quando ouvir HEY"],
    13: ["Botao X"],
    14: ["Botao X"],
    15: ["Reporter do Channel 5:",
         "Ulala (22 anos)"],
    16: ["Voz de apoio:",
         "Fuse (44 anos)"],
    17: ["Ricos",
         "dancando feito loucos"],
    18: ["Garconete e chef",
         "dancando feito loucos"],
    19: ["Os viloes:",
         "Trupe de danca desconhecida"],
    20: ["Capturados",
         "Passageiros comuns"],
    21: ["Guia espacial",
         "dancando feito louca"],
    22: ["Guia espacial",
         "dancando feito louca DE NOVO"],
    23: ["Somos conhecidos como os Rhythm Rogues"],
    24: ["Voce nao nos engana mais"],
    25: ["Voce nao para de dancar"],
    26: ["Mexa os pes e nao perca o ritmo"],
    27: ["( Botao O )"],
    28: ["( Botao O )"],
    29: ["( Botao X )"],
    30: ["( Botao X )"],
    31: ["( Botao X )"],
    32: ["( Botao X- )"],
    33: ["( Botao X--- )"],
    34: ["( Botao X---, Botao X)"],
})

# ================================================================
# R12CAP_E.BIN (97 entries - Report 1 Part 2 - Boss Purge Intro)
# ================================================================
tb("R12CAP_E.BIN", {
    0: ["Flash de Noticias"],
    1: ["Botao X"],
    2: ["Botao X"],
    3: ["Os indices de audiencia determinam",
        "quantas estrelas voce ganha"],
    4: ["Game over quando as estrelas acabarem"],
    5: ["Dancarino-lider, Rhythm Rogues"],
    6: ["Dancarino-lider (2a geracao), Rhythm Rogues"],
    7: ["Mecha Robo Cantor 01",
        "Kin Kon Kan"],
    8: ["Mecha Robo Cantor 01",
        "Kin Kon Kan (ver 2.0)"],
    9: ["Me chamam de Purge!"],
    10: ["Prazer em conhece-la"],
    11: ["Esse parece ser dureza"],
    12: ["Eu faco a galaxia dancar pra mim!"],
    13: ["Danca, danca, nao de chance a ele!"],
    14: ["Ulala, hora de lutar!"],
    15: ["Doce, esperta e sexy, essa sou eu!"],
    16: ["Danca, danca, e cale a boca dele"],
    17: ["Danca, danca, e cale a boca dele."],
    18: ["Vou fazer voce dancar, dancar pra mim!"],
    19: ["Juro que vou fazer voce dancar pra mim!"],
    20: ["Voce nao tem amigos, mas nao desista!"],
    21: ["Voce esta sozinha, mas ainda da!"],
    22: ["Arrasando na galaxia com nossos passos!"],
    23: ["Vamos te arrasar com nossos grooves!"],
    24: ["Voce tem uns passos, ein, docinho!"],
    25: ["Oh, baby, olha voce dancando!"],
    26: ["Sim, e isso ai! Continua!"],
    27: ["Como voce vai lidar com isso"],
    28: ["Observe bem"],
    29: ["Vamos la, faz!"],
    30: ["Sim, baby!"],
    31: ["Sera que aguenta."],
    32: ["Observe bem,"],
    33: ["Entao ta,"],
    34: ["Hora do grand finale!"],
    35: ["Cuidado!"],
    36: ["Se prepara pra essa!"],
    37: ["Vai, vai, Ulala!"],
    38: ["Agora eu fico serio!"],
    39: ["Entao ta,"],
    40: ["Olha so pra mim!"],
    41: ["Cuidado com essa!"],
    42: ["Eu nunca desisto!!"],
    43: ["O tiro final!"],
    44: ["O tiro final!"],
    45: ["Algo assim"],
    46: ["Abra os ouvidos"],
    47: ["Vai, vai!"],
    48: ["Um passo assim?!"],
    49: ["Abra os ouvidos"],
    50: ["Que tal isso!"],
    51: ["Sim, vai la, Ulala!!!"],
    52: ["Hora do grand finale!"],
    # 53-93 are empty
    94: ["Voce nao tem chance!"],
    95: ["Danca, danca, nao perca essa luta!"],
    96: ["Sei nao, viu!"],
})
# Fill empty entries 53-93
for i in range(53, 94):
    t("R12CAP_E.BIN", i, [""])

# ================================================================
# R20CAP_E.BIN (5 entries - Report 2 intro)
# ================================================================
tb("R20CAP_E.BIN", {
    0: ["Hora das Moro-Noticias"],
    1: ["O Presidente Espacial Peace"],
    2: ["esta visitando o Parque Espacial"],
    3: ["Oopii, moro-moro!!"],
    4: ["A Vinganca da Natureza!"],
})

# ================================================================
# R21CAP_E.BIN (15 entries - Report 2 Part 1)
# ================================================================
tb("R21CAP_E.BIN", {
    0: ["Flash de Noticias"],
    1: ["Pressione o botao O quando ouvir HEY!"],
    2: ["Pressione o botao O quando ouvir HEY!"],
    3: ["Chu----- (Segure o botao A)"],
    4: ["Chu----- (Segure o botao X)"],
    5: ["\"Culinaria Gostosa (reprise)\"",
        "nao sera transmitido hoje"],
    6: ["Comandante de Campo dos Rhythm Rogues",
        "\" Shadow \""],
    7: ["Reporters concorrentes"],
    8: ["Criancas do Ensino Fundamental",
        "capturadas pela planta carnivora."],
    9: ["Professor espacial e alunos",
        "cedendo ao ritmo"],
    10: ["Professor Espacial",
         "que nao para de dancar"],
    11: ["Local de transmissao"],
    12: ["Filmado no belissimo Parque Espacial"],
    13: ["Apresentado por UGA"],
    14: ["Com apoio de WM"],
})

# ================================================================
# R22CAP_E.BIN (18 entries - Report 2 Part 2)
# ================================================================
tb("R22CAP_E.BIN", {
    0: ["Flash de Noticias"],
    1: ["Pressione BAIXO para tocar guitarra!"],
    2: ["Reporter concorrente:",
        "      ",
        "Pudding"],
    3: ["Do Channel 42:",
        "Pudding e seus Guarda-Costas"],
    4: ["Imitadora:",
        "         ",
        "Padding"],
    5: ["Senhora dos Passaros Espaciais",
        "dancando sem parar no momento"],
    6: ["Treinador de Caes Espaciais",
        "num funk danado no momento"],
    7: ["Capturado",
        "Homem-Passaro"],
    8: [""],
    9: ["Padding e seus guarda-costas"],
    10: ["Reporter concorrente:",
         "Nossa grande",
         "Pudding"],
    11: ["Mantenha a terra linda"],
    12: ["( CIMA )"],
    13: ["( Botao O )"],
    14: ["( Botao X )"],
    15: ["( Botao O )"],
    16: ["( Botao X )"],
    17: ["Imitadora:",
         "Nossa grande",
         "Padding"],
})

# ================================================================
# R23CAP_E.BIN (22 entries - Report 2 Part 3 - Boss)
# ================================================================
tb("R23CAP_E.BIN", {
    0: ["O numero de estrelas",
        "e determinado pelos indices de audiencia"],
    1: ["Game over quando as estrelas acabarem"],
    2: ["Lider de Campo dos Rhythm Rogues:",
        "Shadow"],
    3: ["Presidente Espacial:",
        "Peace"],
    4: ["Mecha de Ataque Cantor 02",
        "Pon Piriri"],
    5: ["Mecha de Ataque Cantor 02",
        "Pon Piriri (melhorado)"],
    6: ["Es-tre-la ninja, esti-lin-gue-sti-lin-gue"],
    7: ["Cuidado ai, U-la-la!"],
    8: ["Esti-lin-gue-em-voce!"],
    9: ["U-la-la-la!"],
    10: ["Toma ESSA!"],
    11: ["Toma AQUELA!"],
    12: ["E que tal ESSA!"],
    13: ["Agora toma essa!"],
    14: ["E toma essa!"],
    15: ["Que tal essa!!"],
    16: ["Toma ESSA, toma AQUELA, e por fim toma ESSA!!"],
    17: ["Argh, toma essa, e aquela! Acabar com voce!!"],
    18: ["Flash de Noticias"],
    19: ["Temperatura ambiente: 35C"],
    20: ["Hihihi!"],
    21: ["Lanca! Lanca-em-voce!"],
})

# ================================================================
# R30CAP_E.BIN (8 entries - Report 3 intro)
# ================================================================
tb("R30CAP_E.BIN", {
    0: ["Hora das Moro-Noticias"],
    1: ["Grawphh! Moro-moro!"],
    2: ["Ainda nao ha noticias"],
    3: ["sobre o paradeiro do Presidente"],
    4: ["Nao so isso, mas 365.969 pessoas"],
    5: ["de toda a galaxia"],
    6: ["foram sequestradas!!"],
    7: ["Conheca a Policia Espacial Sexy!"],
})

# ================================================================
# R31CAP_E.BIN (44 entries - Report 3 Part 1)
# ================================================================
tb("R31CAP_E.BIN", {
    0: ["Flash de Noticias"],
    1: ["Pressione BAIXO para bater no tambor!"],
    2: ["Nave da Policia Espacial:",
        "The Playgirl"],
    3: ["Colega de trabalho:",
        "Noize"],
    4: ["Policia Espacial:",
        "Pine e As Sexy 1 e 2"],
    5: ["Policia Espacial",
        "Texas e As Sexy 1 e 2"],
    6: [""],
    7: [""],
    8: [""],
    9: ["Me chamam de Pine (Pine!)"],
    10: ["Me chamam de Texas (Texas!)"],
    11: ["Policia Espacial de Leste Venus."],
    12: ["Policia Espacial de Oeste Vixen."],
    13: ["Se tem crime, (tem crime)"],
    14: ["Voce anda por ai (la no beco)"],
    15: ["Vamos pegar ele na ronda da manha!"],
    16: ["Estaremos la pra selar seu destino!"],
    17: ["Envolvido num crime (crime pesado)"],
    18: ["Voce nao presta (nao presta, nao presta)"],
    19: ["(O ritmo!)"],
    20: ["( Botao X )"],
    21: ["( Botao X )"],
    22: ["( BAIXO )"],
    23: ["Nave da Policia Espacial",
         "The Gold 'n Silver"],
    24: ["( X )"],
    25: ["     ( X )"],
    26: ["              ( BAIXO )"],
    27: ["                     ( X )"],
    28: ["( X )"],
    29: ["      ( X )"],
    30: [""],
    31: [""],
    32: [""],
    33: [""],
    34: [""],
    35: [""],
    36: [""],
    37: [""],
    38: [""],
    39: [""],
    40: [""],
    41: [""],
    42: [""],
    43: ["(destino!)"],
})

# ================================================================
# R40CAP_E.BIN (9 entries - Report 4 intro)
# ================================================================
tb("R40CAP_E.BIN", {
    0: ["Hora das Moro-Noticias"],
    1: ["Estacoes de transmissao por toda a galaxia"],
    2: ["estao sendo atacadas pelos Rhythm Rogues"],
    3: ["Gwaah, moro-moro!!"],
    4: ["Channel 42&"],
    5: ["Channel 1&"],
    6: ["Channel 88&"],
    7: ["Todos estao em maus lencois!"],
    8: ["O fim do Space Channel 5?!"],
})

# ================================================================
# R41CAP_E.BIN (9 entries - Report 4 Part 1)
# ================================================================
tb("R41CAP_E.BIN", {
    0: [""],
    1: [""],
    2: ["Equipe de Resgate",
        "(numa sinuca de bico)"],
    3: ["Lider da Equipe de Resgate",
        "(numa sinuca de bico)"],
    4: ["Musica da Equipe de Resgate"],
    5: ["Resgate!!"],
    6: ["Urk!"],
    7: ["Nave de Resgate",
        "(sob ataque)"],
    8: ["Hrk!"],
})

# ================================================================
# R42CAP_E.BIN (45 entries - Report 4 Part 2)
# ================================================================
tb("R42CAP_E.BIN", {
    0: ["Esquerda---!"],
    1: ["Direita--!"],
    2: ["Lideres de Torcida Espaciais",
        "Torcendo contra a vontade"],
    3: ["Capita das Lideres de Torcida Espaciais",
        "Torcendo contra a vontade"],
    4: [""],
    5: ["Robo de Seguranca",
        "Evila (aliada)"],
    6: [""],
    7: [""],
    8: ["Chefe da Estacao Michael",
        "Eu preferia estar fazendo moonwalk!"],
    9: [""],
    10: [""],
    11: ["Vamos la, Atire!"],
    12: ["Vai, Vai, Channel 5!"],
    13: ["Esquerda, chu, direita, chu!"],
    14: ["Amor!"],
    15: ["Hey Hey Resgate!"],
    16: ["A-T-I-R-E-"],
    17: [""],
    18: ["Atire neles!"],
    19: ["Vai Vai Vai Vai!"],
    20: ["Space Channel 5!"],
    21: ["Vamos Dancar!"],
    22: ["Vamos Atirar!"],
    23: ["Sexy, Ulala, YEAH!"],
    24: ["Hoje a noite e de Beat It!"],
    25: ["Chu!"],
    26: ["Hey!"],
    27: ["1-2-3-4-"],
    28: ["Channel 5!"],
    29: ["Vamos la!"],
    30: ["Vamos atirar!"],
    31: ["Atirar! Atirar!"],
    32: ["Robo de Seguranca do Channel 5"],
    33: ["Lider de Torcida Espacial (Novata)",
         "Essa nao e a torcida que ela aprendeu!"],
    34: ["\"O\""],
    35: ["\"D\""],
    36: ["\"E\""],
    37: ["\"N\""],
    38: ["\"ODEN\""],
    39: ["Esquerda--"],
    40: ["Esquerda--, Botao O"],
    41: ["Direita--"],
    42: ["Direita--, Botao O"],
    43: ["Esquerda--, Botao O"],
    44: ["Direita--, Botao O"],
})

# ================================================================
# R43CAP_E.BIN (17 entries - Report 4 Part 3 - Purge)
# ================================================================
tb("R43CAP_E.BIN", {
    0: ["Flash de Noticias"],
    1: ["Purge roubou",
        "o Sistema de Transmissao Espacial (Antena)"],
    2: ["Lider dos Rhythm Rogues",
        "Purge"],
    3: ["Lider dos Rhythm Rogues",
        "Purge Junior"],
    4: ["Mecha dos Rhythm Rogues",
        "Peace Carrier"],
    5: ["Mecha dos Rhythm Rogues",
        "Peace Carrier (modelo classico)"],
    6: ["Robo de Fusao Cantor",
        "Purge, o Rei"],
    7: ["Robo de Fusao Cantor",
        "Purge, o Rei, Junior"],
    8: ["Pressione o oposto do que ouvir,",
        "e depois o botao X."],
    9: ["Pressione o oposto do que ouvir,",
        "e depois o botao X."],
    10: ["Pressione BAIXO para cantar!"],
    11: [""],
    12: ["Tocando ao contrario!"],
    13: ["Tocando ao contrario!"],
    14: ["Nao acerte o presidente"],
    15: ["Nao acerte o presidente"],
    16: ["DANCE!"],
})

# ================================================================
# R44CAP_E.BIN (2 entries)
# ================================================================
tb("R44CAP_E.BIN", {
    0: ["Flash de Noticias"],
    1: ["Voce precisa dancar bem",
        "consecutivamente para criar energia!"],
})

# ================================================================
# R50CAP_E.BIN (1 entry - Report 5)
# ================================================================
tb("R50CAP_E.BIN", {
    0: ["Zona Misteriosa"],
})

# ================================================================
# R51CAP_E.BIN (9 entries - Report 5 Part 1)
# ================================================================
tb("R51CAP_E.BIN", {
    0: ["Flash de Noticias"],
    1: ["Report Ao Vivo por Circuito de Emergencia"],
    2: ["Nao acredito que vim aqui, moro-moro!"],
    3: ["Eles nos encontraram!"],
    4: [""],
    5: [""],
    6: ["Memorize as poses do robo!"],
    7: ["( Botao X )"],
    8: ["( Botao X )"],
})

# ================================================================
# R52CAP_E.BIN (10 entries - Report 5 Part 2)
# ================================================================
tb("R52CAP_E.BIN", {
    0: ["Flash de Noticias"],
    1: ["Use o raio do botao O para acertar",
        "o verdadeiro!"],
    2: ["Banda Robotica:",
        "The Shadows"],
    3: ["Banda Robotica:",
        "The Shadows (Reunidos)"],
    4: ["Hyahh!"],
    5: ["Homem em busca da verdade:",
        "Jaguar"],
    6: ["Qual de nos nao pertence ao grupo"],
    7: ["Qual deles nao pertence ao grupo"],
    8: ["Qual e o verdadeiro?"],
    9: ["Qual e o verdadeiro?"],
})

# ================================================================
# R60CAP_E.BIN (9 entries - Report 6 intro - Purge)
# ================================================================
tb("R60CAP_E.BIN", {
    0: ["O Relatorio Purge"],
    1: ["O teste da Onda foi um sucesso!",
        "Toda Morodia danca pra mim!"],
    2: ["Toda a vasta galaxia dan-ca pra mim."],
    3: ["Sim, vou fazer cada um de voces mu-ito fe-liz!"],
    4: ["Eu me surpreendo!"],
    5: ["Purge Genio!"],
    6: ["Canhao de Groove Balistico"],
    7: ["O teste do Canhao de Groove Balistico foi",
        "um sucesso! Toda Morodia danca pra mim!"],
    8: ["Especial de TV do Purge"],
})

# ================================================================
# R61CAP_E.BIN (19 entries - Report 6 Part 1)
# ================================================================
tb("R61CAP_E.BIN", {
    0: ["Flash de Noticias"],
    1: ["A energia de danca da plateia",
        "esta carregando o Canhao de Groove Balistico"],
    2: ["O Canhao de Groove Balistico continua carregando!!"],
    3: ["A carga do Canhao de Groove Balistico esta completa"],
    4: ["Todos estao sob controle!"],
    5: ["Ulala!"],
    6: ["Nao tem como parar agora!"],
    7: ["Eu vou acabar com isso!"],
    8: ["Esse e o fim da linha!"],
    9: ["Nao, eu nao vou parar!"],
    10: ["Todos dancem comigo."],
    11: ["Sem chance!"],
    12: ["Agora dancem, todos!"],
    13: ["Para ai, moro-moro!"],
    14: ["Ulala"],
    15: ["Purge!"],
    16: ["Puuuuurge!!"],
    17: ["Super Traje:",
         "Purge, o Grande"],
    18: ["Super Traje:",
         "Purge, o Grande (de volta com vinganca)"],
})

# ================================================================
# R62CAP_E.BIN (34 entries - Report 6 Part 2 - Finale)
# ================================================================
tb("R62CAP_E.BIN", {
    0: [""],
    1: ["Flash de Noticias"],
    2: ["Pressione BAIXO para bater palmas!"],
    3: ["A carga do Canhao de Groove Balistico",
        "foi interrompida."],
    4: ["Pressione BAIXO junto com a melodia!"],
    5: ["Ulala!"],
    6: ["Super Traje:",
        "Purge, o Grande"],
    7: ["Super Traje:",
        "Purge, o Grande (de volta com vinganca)"],
    8: ["La, lalala-"],
    9: ["Vamos la, VAI!"],
    10: ["La, lalalala-"],
    11: ["Isso e Suficiente!"],
    12: ["Lalalalalala-"],
    13: ["Yeah, Baby. Yeah, Vamos la."],
    14: ["Laala, lala-"],
    15: ["Cantem Juntos!"],
    16: ["Laala, lala-"],
    17: ["Voce Tambem, Cante!"],
    18: ["La, la, la!"],
    19: ["U, la, la!"],
    20: ["Chu chu chu"],
    21: ["Cante Com a Gente"],
    22: ["Cante Com a Gente"],
    23: ["Todos de uma vez"],
    24: ["Cante Com a Gente"],
    25: ["De Coracao a Coracao"],
    26: ["O que e o Coracao?"],
    27: ["Nos Temos Forca"],
    28: ["Que Forca e Essa?"],
    29: ["Forca do Amor"],
    30: ["Forca do Amor"],
    31: ["Forca do Amor"],
    32: ["E assim foi..."],
    33: ["Que a galaxia inteira realmente dancou."],
})

print(f"[CAP_E files] Translations applied: {count}")

# ================================================================
# NOW: ITALIAN SOURCE FILES (SYCAP, VOCAP, MUCAP)
# These are IT->PT-BR translations
# ================================================================

# ================================================================
# R1SYCAP_I.BIN (80 entries - System commentary Report 1)
# ================================================================
tb("R1SYCAP_I.BIN", {
    0: ["Voce esta piorando!"],
    1: ["Voce consegue fazer melhor!"],
    2: ["Ate um macaco consegue!"],
    3: ["Nao ta funcionando!"],
    4: ["Calma, e mira direito!"],
    5: ["Mira bem!"],
    6: ["Que que ta acontecendo?"],
    7: ["Nao consigo olhar!"],
    8: ["Me mostra o que voce sabe!"],
    9: ["Olha bem pra eles!"],
    10: ["Voce ta tentando?"],
    11: ["NAO ta dando certo!"],
    12: ["Vai, Ulala!"],
    13: ["Aperte o botao O quando ouvir \"HEY\"!"],
    14: ["Vamos la! Aperte os botoes certos!"],
    15: ["Muito bem!"],
    16: ["Assim que se faz!"],
    17: ["Bem, bem, bem!!!"],
    18: ["Assim que eu gosto, baby!"],
    19: ["Otima danca!"],
    20: ["Belo tiro!"],
    21: ["Ta indo bem, garota, muito bem!"],
    22: ["Nada mal!"],
    23: ["Um trabalho nada mal, sim!"],
    24: ["Voce tem boas chances!"],
    25: ["Voce e demais!"],
    26: ["Muito bem, eu diria!"],
    27: ["Mais um erro e boa noite!"],
    28: ["Os indices de audiencia estao em perigo!"],
    29: ["Mais um erro e a gente fecha!"],
    30: ["Mais um erro e ja era!!"],
    31: ["Issimo, Ulala!"],
    32: ["Muito bem, muito bem mesmo!"],
    33: ["Ta indo bem, Ulala!"],
    34: ["Belos passos, Ulala!"],
    35: ["Voce e fabulosa, Ulala!"],
    36: ["Que ta pegando, Ulala?!"],
    37: ["O que houve com seus reflexos, Ulala?"],
    38: ["Voce nao vai conseguir, Ulala!"],
    39: ["Se esforci, Ulala!"],
    40: ["Voce errou...TUDO!!"],
    41: ["Nao acertou nenhum!"],
    42: ["Voce perdeu, feio."],
    43: ["Resgate bem-sucedido!"],
    44: ["Um super resgate!"],
    45: ["Resgate fracassado!"],
    46: ["O resgate foi um fracasso total!"],
    47: ["Nos salvamos eles!"],
    48: ["Nos salvamos eles!"],
    49: ["O resgate foi um sucesso total!"],
    50: ["O resgate foi completamente bem-sucedido!"],
    51: ["Nos arrasamos eles!"],
    52: ["Nos esmagamos eles!"],
    53: ["Nao salvamos ninguem!"],
    54: ["Falhamos!"],
    55: ["Nao vencemos nenhum!"],
    56: ["Falhamos!"],
    57: ["Nao vencemos nenhum!"],
    58: ["Fomos um desastre total!"],
    59: [""],
    60: ["Ah, qual e!"],
    61: ["Que pena..."],
    62: ["Belo tiro!!"],
    63: ["Voce e uma bomba!!"],
    64: ["Bom! Bom trabalho!"],
    65: ["Espetacular, Ulala!",
         "Ah, ah, ah, ah, ah!!",
         "Fuse, se acalma!!"],
    66: ["Nada mal, Ulala!",
         "Aiiihh!!",
         "Tragam um pano!!"],
    67: ["Bom, nada mal, Ulala!",
         "Oh, Noize, pode fazer um cafe!?",
         "Ja, Fuse!"],
    68: ["O que? O programa foi cancelado?"],
    69: ["Ehh?! A tela!!!"],
    70: ["Vamos la, Ulala!!"],
    71: ["Ulala, agora podemos ir pra casa."],
    72: ["Ulala, vamos tentar de novo!"],
    73: ["Ja teve o bastante?"],
    74: ["Nao tem mais o que fazer!!"],
    75: ["Vai la, se divirtam!"],
    76: ["Voce nao e tao forte quanto eu pensava."],
    77: ["Desculpa, mas voce e uma negacao."],
    78: ["Voce e o as que dizem."],
    79: ["Heh, heh, heh, heh, heh!"],
})

# ================================================================
# R2SYCAP_I.BIN (117 entries - System commentary Report 2)
# Many are repetitions from R1SYCAP with some additions
# ================================================================
tb("R2SYCAP_I.BIN", {
    0: ["Voce esta piorando!"],
    1: ["Voce consegue fazer melhor!"],
    2: ["Nossos indices de audiencia estao indo pro lixo..."],
    3: ["Continua tentando!"],
    4: ["Ate um macaco consegue!"],
    5: ["Calma, e mira direito!"],
    6: ["Mira bem!"],
    7: ["Oh, nao!!"],
    8: ["Nao consigo olhar!"],
    9: ["Por favor, Ulala!"],
    10: ["Se esforci!"],
    11: ["Pra onde voce ta mirando?"],
    12: ["Vamos! O professor vai se dar mal!"],
    13: ["Ah, qual e! Voce ta errando um monte!"],
    14: ["Aperte o botao O quando ouvir \"HEY\"!"],
    15: ["Aperte o botao O quando ouvir \"HEY\"!"],
    16: ["Vamos la! Aperte os botoes certos!"],
    17: ["Muito bem!"],
    18: ["Fantastico!"],
    19: ["Olha como os indices de audiencia sobem!"],
    20: ["Assim que se faz!"],
    21: ["Bem, bem, bem!!!"],
    22: ["Assim que eu gosto, baby!"],
    23: ["Continua assim!"],
    24: ["Otima danca!"],
    25: ["Belo tiro!"],
    26: ["Wow!!"],
    27: ["Bom, continua assim!"],
    28: ["Belos passos!"],
    29: ["Nada mal!"],
    30: ["Nada mal!"],
    31: ["Um trabalho nada mal, sim!"],
    32: ["Acho que ja estamos chegando!"],
    33: ["Voce tem muito talento!"],
    34: ["Acho que voce vai conseguir!"],
    35: ["No geral, muito bem!"],
    36: ["Voce e demais!"],
    37: ["Muito bem, eu diria!"],
    38: ["Perfeito!"],
    39: ["Perfeito, de novo!"],
    40: ["Tres vezes seguidas!"],
    41: ["Isso sim e dancar!"],
    42: ["Olha passaros, passaros!"],
    43: ["Um passaro, um passaro!"],
    44: ["Mais um erro e boa noite!"],
    45: ["Os indices de audiencia estao em perigo!"],
    46: ["Mais um erro e a gente fecha!"],
    47: ["Mais um erro e ja era!!"],
    48: ["Voce ta meio desajeitada!"],
    49: ["Siiim!"],
    50: ["Vai, linda, da o seu melhor!"],
    51: ["Sim, eu sou demais!"],
    52: ["Issimo, Ulala!"],
    53: ["Muito bem, muito bem mesmo!"],
    54: ["Ta indo bem, Ulala!"],
    55: ["Belos passos, Ulala!"],
    56: ["Nada mal, Ulala!"],
    57: ["Voce e fabulosa, Ulala!"],
    58: ["Manda bem, garota! Wowww!"],
    59: ["Fan-tas-ti-co!!"],
    60: ["Faz a gente sonhar!!"],
    61: ["O que houve com seus reflexos, Ulala?"],
    62: ["Voce nao vai conseguir, Ulala!"],
    63: ["Se esforci, Ulala!"],
    64: ["Voce nem ta tentando!"],
    65: ["Ta de brincadeira?"],
    66: ["Voce ta perdendo feio, Ulala!"],
    67: ["Se esforci, Ulala!"],
    68: ["Voce errou...TUDO!!"],
    69: ["Nao acertou nenhum!"],
    70: ["Que desastre!"],
    71: ["Voce perdeu, feio."],
    72: ["Resgate bem-sucedido!"],
    73: ["Um super resgate!"],
    74: ["Resgate fracassado!"],
    75: ["O resgate foi um fracasso total!"],
    76: ["Nos salvamos eles!"],
    77: ["Nos salvamos eles!"],
    78: ["O resgate foi um sucesso total!"],
    79: ["O resgate foi completamente bem-sucedido!"],
    80: [""],
    81: ["Nos arrasamos eles!"],
    82: ["Nos esmagamos eles!"],
    83: [""],
    84: ["Nao salvamos ninguem!"],
    85: ["Falhamos!"],
    86: ["Nao vencemos nenhum!"],
    87: ["Fomos um desastre total!"],
    88: ["Eu venci a Pudding!"],
    89: ["Eu venci a Padding!"],
    90: ["Nos vencemos sem problemas!"],
    91: ["A Pudding me venceu!"],
    92: ["A Padding me venceu!"],
    93: ["Eles humilharam a gente!"],
    94: [""],
    95: ["Ah, qual e, Ulala!"],
    96: ["Que pena..."],
    97: ["Facil, facil!"],
    98: ["Voce e demais!"],
    99: ["Que desastre!"],
    100: ["Belo passo!"],
    101: ["Que espetaculo!"],
    102: ["Aiiiaaahhhhhh!!"],
    103: ["Bom! Bom trabalho!"],
    104: ["Espetacular, Ulala!",
          "Ah, ah, ah, ah, ah!!",
          "Fuse, se acalma!!"],
    105: ["Nada mal, Ulala!",
          "Aiiihh!!",
          "Tragam um pano!!"],
    106: ["Bom, nada mal, Ulala!",
          "Oh, Noize, pode fazer um cafe!?",
          "Ja, Fuse!"],
    107: ["O que? O programa foi cancelado?"],
    108: ["Ehh?! A tela!!!"],
    109: ["Vamos la, Ulala!!"],
    110: ["Ulala, agora podemos ir pra casa."],
    111: ["Ulala, vamos tentar de novo!"],
    112: ["Ja teve o bastante?"],
    113: ["Nao tem mais o que fazer!!"],
    114: ["Olha! E um passaro!"],
    115: ["E um cachorro!"],
    116: ["Olha! E um cachorro!"],
})

# ================================================================
# R3SYCAP_I.BIN (41 entries - System commentary Report 3)
# ================================================================
tb("R3SYCAP_I.BIN", {
    0: ["Fantastico!"],
    1: ["Bem, bem, bem!!!"],
    2: ["Assim que eu gosto, baby!"],
    3: ["Wow!!"],
    4: ["Nada mal!"],
    5: ["Acho que ja estamos chegando!"],
    6: ["Voce tem muito talento!"],
    7: ["Acho que voce vai conseguir!"],
    8: ["Perfeito!"],
    9: ["Perfeito, de novo!"],
    10: ["Mmm... Seeeexy"],
    11: ["Deeemais"],
    12: ["Mais um erro e a gente fecha!"],
    13: ["Mais um erro e ja era!!"],
    14: ["Issimo, Ulala!"],
    15: ["Belos passos, Ulala!"],
    16: ["Mandou bem, Ulala!"],
    17: ["Oh, Ulala, voce sabe como me fazer feliz!"],
    18: ["Ooh ooh ooh!!!"],
    19: ["Eu venci a Pine!"],
    20: ["Eu venci a Texas!"],
    21: ["Nos vencemos sem problemas!"],
    22: [""],
    23: ["Nao desanima!"],
    24: ["Uma porcaria!"],
    25: ["Wow! Issimo!"],
    26: ["Hurrraaaaa!"],
    27: [""],
    28: ["Espetacular, Ulala!",
         "Ah, ah, ah, ah, ah!!",
         "Fuse, se acalma!!"],
    29: ["Nada mal, Ulala!",
         "<crash>  Aiiihh!!",
         "Tragam um pano!!"],
    30: ["Bom, nada mal, Ulala!",
         "Oh, Noize, pode fazer um cafe!?",
         "Ja, Fuse!"],
    31: ["O que? O programa foi cancelado?"],
    32: ["Ehh?! A tela!!!"],
    33: ["Vamos la, Ulala!!"],
    34: ["Ulala, agora podemos ir pra casa."],
    35: ["Ulala, vamos tentar de novo!"],
    36: ["Ja teve o bastante?"],
    37: ["Nao tem mais o que fazer!!"],
    38: ["Um ritmo anti-crime!"],
    39: ["Tenta bater meu ritmo!!"],
    40: ["Viva os ritmos estrondosos!"],
})

# ================================================================
# R4SYCAP_I.BIN (97 entries - System commentary Report 4)
# ================================================================
tb("R4SYCAP_I.BIN", {
    0: ["Voce esta piorando!"],
    1: ["Vamos!"],
    2: ["Continua tentando!"],
    3: ["Ate um macaco consegue!"],
    4: ["Nao ta funcionando!"],
    5: ["Ulala, me mostra o que voce sabe!"],
    6: ["Nao consigo olhar!"],
    7: ["Por favor, Ulala!"],
    8: ["Nao desista, Ulala!"],
    9: ["Coragem, Ulala!"],
    10: ["Naooooooo!"],
    11: ["Fantastico!"],
    12: ["Bem, bem, bem!!!"],
    13: ["Belo tiro!"],
    14: ["Wow!!"],
    15: ["Belos passos!"],
    16: ["Nada mal!"],
    17: ["Um trabalho nada mal, sim!"],
    18: ["Voce tem muito talento!"],
    19: ["Acho que voce vai conseguir!"],
    20: ["No geral, muito bem!"],
    21: ["Voce e demais!"],
    22: ["Perfeito!"],
    23: ["Perfeito, de novo!"],
    24: ["Caramba, voce e um fenomeno..."],
    25: ["Que amor!"],
    26: ["Belo tiro!"],
    27: ["Mais um erro e boa noite!"],
    28: ["Os indices de audiencia estao em perigo!"],
    29: ["Mais um erro e a gente fecha!"],
    30: ["Mais um erro e ja era!!"],
    31: ["Ulala, voce precisa mirar melhor!"],
    32: ["Mira melhor, Ulala!"],
    33: ["Por favor, Ulala!"],
    34: ["Voce precisa apertar os botoes certos!!"],
    35: ["Ta indo bem!"],
    36: ["Assim que eu gosto!"],
    37: ["Muito bem!"],
    38: ["Acabou pra gente!"],
    39: ["Mais um erro e a gente perde!"],
    40: ["Mais um erro e tudo perdido!"],
    41: ["Muito bem, muito bem mesmo!"],
    42: ["Issimo, Ulala!"],
    43: ["Manda bem, garota! Wowww!"],
    44: ["Mandou bem, Ulala!"],
    45: ["Fan-tas-ti-co!!"],
    46: ["Faz a gente sonhar!!"],
    47: ["Diamantes sao eternos!"],
    48: ["Doce, esperta e sexy!"],
    49: ["Bom trabalho! Que emocao!!"],
    50: ["Sim! 110%, fantastico, linda!"],
    51: ["Voce ta perdendo feio, Ulala!"],
    52: ["Que desastre!"],
    53: ["O que voce fez?!"],
    54: ["Nos salvamos eles!"],
    55: ["Nos salvamos eles!"],
    56: ["O resgate foi um sucesso total!"],
    57: ["O resgate foi completamente bem-sucedido!"],
    58: ["Nos arrasamos eles!"],
    59: ["Nos esmagamos eles!"],
    60: ["Quase nao salvamos ninguem..."],
    61: ["Quase nao vencemos ninguem..."],
    62: ["Nao salvamos ninguem!"],
    63: ["Falhamos!"],
    64: ["Nao vencemos nenhum!"],
    65: ["Fomos um desastre total!"],
    66: ["Resgate bem-sucedido!"],
    67: ["Um super resgate!"],
    68: ["Resgate fracassado!"],
    69: ["O resgate foi um fracasso total!"],
    70: [""],
    71: ["Pior impossivel!"],
    72: ["Ta de brincadeira?"],
    73: ["Fantastico!"],
    74: ["Grrrrrrrrr!"],
    75: ["Que pena!",
         "Voce nao fez o passo com Michael..."],
    76: ["Voce perdeu a chance",
         "com Michael\u00a4"],
    77: ["Que forca!"],
    78: ["Ohhhhhhhhhh!"],
    79: ["Bom! Bom trabalho!"],
    80: ["Espetacular, Ulala!",
         "Ah, ah, ah, ah, ah!!",
         "Fuse, se acalma!!"],
    81: ["Nada mal, Ulala!",
         "<crash>  Aiiihh!!",
         "Tragam um pano!!"],
    82: ["Bom, nada mal, Ulala!",
         "Oh, Noize, pode fazer um cafe!?",
         "Ja, Fuse!"],
    83: ["O que? O programa foi cancelado?"],
    84: ["Ehh?! A tela!!!"],
    85: ["Vamos la, Ulala!!"],
    86: ["Ulala, agora podemos ir pra casa."],
    87: ["Ulala, vamos tentar de novo!"],
    88: ["Ja teve o bastante?"],
    89: ["Nao tem mais o que fazer!!"],
    90: ["Acha que pode me vencer?"],
    91: ["E sua ultima chance de desistir!!"],
    92: ["Ohhhhhhhhhh!"],
    93: ["A todos os reporters, respondam.",
         "Aqui e a Policia Espacial",
         "chhkkzzzz... Respondam imediatamente..."],
    94: ["Aqui e a Pine. Precisamos de ajuda...",
         "Cambio\u00a4"],
    95: ["Aqui e a Pine. Temos uma emergencia.",
         "Precisamos de ajuda... Cambio..."],
    96: ["Aqui e a Pine. Nao espero muito de voces,",
         "mas nos ajudem. Cambio."],
})

# ================================================================
# R5SYCAP_I.BIN (62 entries - System commentary Report 5)
# ================================================================
tb("R5SYCAP_I.BIN", {
    0: ["Por favor, Ulala!"],
    1: ["Ai! Ulala, contamos com voce!"],
    2: ["Pra onde voce ta mirando?!"],
    3: ["De mal a pior!"],
    4: ["Nao desista!"],
    5: ["Fabuloso!"],
    6: ["Da o seu melhor!"],
    7: ["Lembra dos comandos!"],
    8: ["Aaaarrrggg!!"],
    9: ["Ta indo bem!"],
    10: ["Sim, continua assim!"],
    11: ["Issimo, fantastico!!"],
    12: ["Muito bem!"],
    13: ["Voce vai conseguir! Continua tentando!"],
    14: ["Sim, sim, sim!"],
    15: ["Perfeito!"],
    16: ["Absolutamente perfeito!"],
    17: ["Acabou pra gente!"],
    18: ["Mais um erro e a gente perde!"],
    19: ["Mais um erro e tudo perdido!"],
    20: ["Wow! Voce foi incrivel, Ulala!"],
    21: ["Ulala, voce sabe das coisas!"],
    22: ["Voce foi absolutamente fantastica, Ulala!"],
    23: ["Ulala, voce e incrivel!"],
    24: ["Absolutamente esplendido, Ulala!"],
    25: ["Ulala, e melhor prestar mais atencao!"],
    26: ["Ulala, nao ta dando!"],
    27: ["Que ta pegando, Ulala?! Por favor!!"],
    28: ["Resgate bem-sucedido!"],
    29: ["Um super resgate!"],
    30: ["Nos salvamos eles!"],
    31: ["Nos salvamos eles!"],
    32: ["O resgate foi um sucesso total!"],
    33: ["O resgate foi completamente bem-sucedido!"],
    34: ["Nos arrasamos eles!"],
    35: ["Nos esmagamos eles!"],
    36: ["Quase nao salvamos ninguem..."],
    37: ["Quase nao vencemos ninguem..."],
    38: ["Nao salvamos ninguem!"],
    39: ["Falhamos!"],
    40: ["Nao vencemos nenhum!"],
    41: ["Fomos um desastre total!"],
    42: ["Nos vencemos sem problemas!"],
    43: [""],
    44: [""],
    45: [""],
    46: [""],
    47: ["O que? O programa foi cancelado?"],
    48: ["Ehh?! A tela!!!"],
    49: ["Vamos la, Ulala!!"],
    50: ["Ulala, agora podemos ir pra casa."],
    51: ["Ulala, vamos tentar de novo!"],
    52: ["Ja teve o bastante?"],
    53: ["Escapamos da armadilha!"],
    54: ["Escapamos da armadilha! Sem problemas!"],
    55: ["Ah, ah, ah, ah, ah!"],
    56: ["Vamos nos divertir juntos!"],
    57: ["Nada mal mesmo..."],
    58: ["Sera que vai durar!"],
    59: ["Hora de uma guitarrada!"],
    60: ["E agora o coro!"],
    61: ["Agora tudo junto!"],
})

# ================================================================
# R6SYCAP_I.BIN (10 entries - System commentary Report 6)
# ================================================================
tb("R6SYCAP_I.BIN", {
    0: [""],
    1: [""],
    2: [""],
    3: [""],
    4: ["O que? O programa foi cancelado?"],
    5: ["Ehh?! A tela!!!"],
    6: ["Vamos la, Ulala!!"],
    7: ["Ulala, agora podemos ir pra casa."],
    8: ["Ulala, vamos tentar de novo!"],
    9: ["Ja teve o bastante?"],
})

# ================================================================
# VOCAP FILES - Voice/Dialogue subtitles (Italian -> PT-BR)
# ================================================================

# R01VOCAP_I.BIN (19 entries - Ulala's Dance voice)
tb("R01VOCAP_I.BIN", {
    0: ["Comeca!! A batalha dos 100 estagios!"],
    1: [""],
    2: [""],
    3: [""],
    4: [""],
    5: [""],
    6: [""],
    7: [""],
    8: [""],
    9: [""],
    10: [""],
    11: [""],
    12: [""],
    13: [""],
    14: ["Wow! Voce conseguiu! Completou todos os 100",
         "estagios! Voce e uma estrela! Viva!!!"],
    15: ["O que foi?!"],
    16: ["Quase!"],
    17: ["Arrgg!! Voce quase conseguiu!"],
    18: ["Ohhhhhh!!!!!!!! Quase, baby!"],
})

# R11VOCAP_I.BIN (36 entries - Report 1 Part 1 voice)
tb("R11VOCAP_I.BIN", {
    0: ["Ola Spacecats!",
        "Na edicao de hoje do Show de Reports da Ulala,",
        "apresentaremos uma materia sobre uma trupe",
        "de danca nao identificada que atacou",
        "esta mesma astronave."],
    1: ["Ola Spacecats!",
        "Como voces podem ver,",
        "hoje eu tenho uma roupa nova!"],
    2: ["Entendido!"],
    3: ["Uhh! Que homem estranho!!"],
    4: ["Hora de uma batalha de danca!"],
    5: ["Vamos dancar!"],
    6: ["Entendido!"],
    7: ["Entendido!"],
    8: ["Vamos atirar!"],
    9: ["Oh, nao. A guia espacial esta apanhando",
        "da gangue de danca!"],
    10: ["Entendido!"],
    11: ["Prontos pra atirar!"],
    12: ["Fiquem com a gente!"],
    13: ["Ulala, fica alerta!"],
    14: ["Entao esses sao os culpados?!"],
    15: ["Aperte o botao X quando ouvir \"chu!\"!"],
    16: ["Eles vem te pegar!"],
    17: ["Nao perca ele de vista e mira bem!"],
    18: ["Use o botao X pra atirar nos robos!"],
    19: ["Aperte esquerda pra Esquerda e",
         "direita pra Direita!"],
    20: ["Agora use o raio pro resgate!",
         "Aperte o botao O quando ouvir HEY!"],
    21: ["Agora vai pro observatorio!"],
    22: ["De novo! Robos chegando!"],
    23: ["Quando ouvir \"chu\" use o raio do botao X!"],
    24: [""],
    25: [""],
    26: [""],
    27: [""],
    28: [""],
    29: [""],
    30: [""],
    31: [""],
    32: [""],
    33: [""],
    34: ["Olha meus passos.",
         "E me copia, sem errar!!"],
    35: ["Quando os coracoes acabarem, voce perde!",
         "Querendo ou nao:"],
})

# R12VOCAP_I.BIN (18 entries - Report 1 Part 2 voice)
tb("R12VOCAP_I.BIN", {
    0: ["Chegamos ao observatorio."],
    1: ["Este lugar e muito perigoso!"],
    2: ["O que foi?!"],
    3: ["Nao importa o que aconteca,",
        "eu vou dancar com tudo!"],
    4: ["Vamos dancar!"],
    5: ["Derrotamos os robos cantores"],
    6: ["O que?!"],
    7: ["Eles voltaram ao ataque!"],
    8: ["Vamos atirar!"],
    9: ["Por hoje e tudo, pessoal.",
        "Da sua Ulala, canal espacial"],
    10: ["Space Channel Fiiiiiiiiiive!!"],
    11: ["Cuidado aqui!"],
    12: ["Vamos levar seus indices de audiencia as alturas!"],
    13: ["La vamos nos de novo!"],
    14: ["Chefe, desculpa a demora.",
         "Agora e sua vez."],
    15: ["Onde voce estava??"],
    16: ["Ahh!"],
    17: ["A festa mal comecou!"],
})

# R21VOCAP_I.BIN (16 entries - Report 2 Part 1 voice)
tb("R21VOCAP_I.BIN", {
    0: ["Ola Spacecats!",
        "Cancelamos nossos programas normais",
        "para trazer esta cobertura especial",
        "ao vivo do Parque Espacial onde",
        "o Presidente Peace foi sequestrado!"],
    1: ["Capturaram criancas do ensino fundamental.",
        "Voce precisa salva-las! Suba na esteira!"],
    2: ["Entendido!"],
    3: ["Vamos atirar!"],
    4: ["Ahhh! A esteira transportadora enlouqueceu!!"],
    5: ["Cuidado pra nao cair, Ulala!"],
    6: ["Os professores espaciais estao sendo obrigados",
        "a dancar ate a morte!"],
    7: [""],
    8: ["Salve eles antes que sejam destruidos."],
    9: ["Vamos dancar!"],
    10: ["Ulala, agora vai pra estufa!"],
    11: ["Ah, ah! Ta vindo algo suspeito."],
    12: ["Quando ouvir \"chu\", aperte o botao X!"],
    13: ["Prontos pra atirar!"],
    14: ["Fiquem com a gente!"],
    15: ["Ehh? Os Rhythm Rogues!?"],
})

# R22VOCAP_I.BIN (39 entries - Report 2 Part 2 voice)
tb("R22VOCAP_I.BIN", {
    0: ["Voce tem que ser mais rapida que os outros reporters!"],
    1: ["Co-como assim?!"],
    2: ["Aperte o direcional pra baixo! Voce tambem",
        "tem uma guitarra!"],
    3: ["Iniciar resgate!"],
    4: ["Ulala, agora vai pra estufa!"],
    5: ["Nao pergunta por que. Faz a pose!"],
    6: ["Vamos tocar!"],
    7: ["Vamos atirar!"],
    8: ["As noticias do Channel 42!"],
    9: ["As noticias do Channel 42!"],
    10: ["Boa noite a todos!"],
    11: ["Sou eu, Pudding!"],
    12: ["Sou eu, Padding!"],
    13: ["Vamos!"],
    14: ["Entendido!"],
    15: ["Entendido!"],
    16: ["Entendido!"],
    17: ["Entendido!"],
    18: ["Duelo de guitarras!"],
    19: ["Chegamos na praca da fonte!"],
    20: ["O que?"],
    21: ["De novo!"],
    22: ["Oh, nao!",
         "A Senhora Passaro foi obrigada a dancar!"],
    23: ["Faz a pose!"],
    24: [""],
    25: [""],
    26: [""],
    27: [""],
    28: ["Oh, nao!",
         "O treinador de caes espaciais foi",
         "obrigado a dancar!"],
    29: ["Eu desisto!"],
    30: ["Foi facil demais!"],
    31: ["Entendido"],
    32: ["Entendido"],
    33: [""],
    34: [""],
    35: [""],
    36: [""],
    37: ["Fiquem com a gente!!"],
    38: ["Fiquem com a gente!!"],
})

# R23VOCAP_I.BIN (50 entries - Report 2 Part 3 voice)
tb("R23VOCAP_I.BIN", {
    0: ["Vamos atirar!"],
    1: ["Rapido!",
        "Vamos elevar seus indices de audiencia!"],
    2: ["Olha! Tentaculos!"],
    3: ["...parece um coco!"],
    4: ["Chegamos na estufa. Que umidade!"],
    5: ["O que e aquilo?!"],
    6: ["E nosso Presidente!",
        "Foi capturado por uma planta!"],
    7: ["Bom, ja que estou aqui, vou tentar salva-lo!"],
    8: ["Pular!"],
    9: ["Ohh!"],
    10: ["Ahhahhhh!"],
    11: [""],
    12: [""],
    13: ["Por favor, agora nao!"],
    14: [""],
    15: ["Que atmosfera empolgante!"],
    16: ["Hora de uma batalha de valsa!"],
    17: ["Vamos dancar!"],
    18: ["Chegamos ao fim do programa.",
         "Ulala se despede do Parque Espacial."],
    19: ["Space Channel Fiiiiiiiiiive!!"],
    20: ["Entendido!"],
    21: ["Acha que vai conseguir, Ulala?!"],
    22: [""],
    23: [""],
    24: [""],
    25: [""],
    26: [""],
    27: [""],
    28: [""],
    29: [""],
    30: [""],
    31: [""],
    32: [""],
    33: [""],
    34: [""],
    35: [""],
    36: ["Oh, a flor!"],
    37: ["Ulala, me salva!",
         "Socorroooooooo!"],
    38: ["Ulala, eu to aqui!"],
    39: ["Se apressa."],
    40: ["Obrigado, Ulala."],
    41: [""],
    42: ["Nos temos o seu grande Presidente."],
    43: ["Nem sonhem em nos deter."],
    44: [""],
    45: ["Hora de uma valsa!"],
    46: ["Hora de uma valsa!"],
    47: ["Prontos pra uma valsa?!"],
    48: [""],
    49: ["Oh, nao!!"],
})

# R31VOCAP_I.BIN (41 entries - Report 3 Part 1 voice)
tb("R31VOCAP_I.BIN", {
    0: ["Bonjour, a todos!",
        "Os criminosos pediram um resgate!",
        "Estamos indo ao local combinado com os sequestradores!"],
    1: ["Pudding!!!"],
    2: ["Padding!!!"],
    3: ["Ehh?"],
    4: ["Entendido!"],
    5: ["Ahiaaaaa!"],
    6: ["Entendido!"],
    7: ["Siiim!"],
    8: ["Batalha de baterias!"],
    9: ["Vamos!"],
    10: ["Prontos pra atirar!"],
    11: ["Fiquem com a gente!!"],
    12: ["O que?"],
    13: ["O que foi?!!"],
    14: ["Entendido!"],
    15: ["Que diabos?!"],
    16: ["Isso, Ulala! Agora chega!!"],
    17: ["Atencao,",
         "estamos indo em direcao a uma nuvem!!"],
    18: ["Nao se deixe vencer, Ulala!"],
    19: ["Da uma forca, Noize!"],
    20: ["Atencao! Os bazucas da Pine estao vindo!"],
    21: ["Quando ouvir \"chu\", aperte o botao X do raio."],
    22: ["Droga!",
         "Entao a noticia do resgate era uma armadilha!?"],
    23: ["Todo mundo de volta a estacao!"],
    24: ["Entendido!"],
    25: [""],
    26: ["O furo e meu!"],
    27: ["A todos os membros da imprensa..."],
    28: ["Aqui fala a Policia Espacial."],
    29: ["Se resistir,"],
    30: ["Voce deveria ter ouvido o aviso!"],
    31: ["Batalha de baterias!"],
    32: ["Vamos tocar!"],
    33: ["Bum-bada-bum-bum"],
    34: ["Batalha de baterias!"],
    35: ["Vamos!"],
    36: [""],
    37: [""],
    38: ["Sai daqui! Vai embora!"],
    39: ["Nao atrapalhe as investigacoes!"],
    40: ["Os fortes sobrevivem!"],
})

# R41VOCAP_I.BIN (12 entries - Report 4 Part 1 voice)
tb("R41VOCAP_I.BIN", {
    0: ["Meu Deus!"],
    1: ["Ulala, voce esta sozinha agora!"],
    2: ["Siga as instrucoes e faca uma bela pose!"],
    3: ["Nao conseguimos separar a capsula!"],
    4: ["Lancamento!"],
    5: ["Limpeza geral!"],
    6: ["Boa noite, queridos telespectadores!",
        "Os estudios do Channel 5 estao numa fria!"],
    7: ["Aqui vai!"],
    8: ["Fiquem com a gente!!"],
    9: ["Entendido!"],
    10: ["Vamos atirar!"],
    11: ["Entendido!"],
})

# R42VOCAP_I.BIN (19 entries - Report 4 Part 2 voice)
tb("R42VOCAP_I.BIN", {
    0: ["Entramos no estudio.",
        "E um verdadeiro desastre!"],
    1: ["Oh! Sinal das lideres de torcida:",
        "58 metros adiante!"],
    2: ["Michael!"],
    3: ["Ehh?!"],
    4: ["Faz a pose!"],
    5: ["Ulala! Vai pro centro!",
        "Space Michael deve estar la!"],
    6: ["Cuidado com os robos escondidos!"],
    7: ["A entrada nao vai abrir ate voce",
        "eliminar todos!"],
    8: ["Siiim!! Avante!"],
    9: ["A entrada nao vai abrir ate voce",
        "vencer todos!"],
    10: ["Assim que se faz! Vaiii!"],
    11: ["Ulala, salva aquelas pobres lideres de torcida!"],
    12: ["Nao! A porta esta fechando!"],
    13: ["Desliza quando eu mandar!"],
    14: ["Ulala, voce precisa salvar Space Michael!"],
    15: ["Voce quase chegou no centro."],
    16: ["Entendido!"],
    17: ["Vamos atirar!"],
    18: ["Vamos dancar!"],
})

# R43VOCAP_I.BIN (39 entries - Report 4 Part 3 voice)
tb("R43VOCAP_I.BIN", {
    0: ["Chegamos ao centro da estacao!"],
    1: ["Queee?"],
    2: ["O que"],
    3: ["O Presidente esta preso la dentro!"],
    4: ["E-Entendido! Quando ouvir",
        "\"ESQUERDA\", va pra \"DIREITA\"!"],
    5: ["Entendido!"],
    6: ["Vamos tocar!"],
    7: ["Entendido!"],
    8: ["Prontos pra atirar!"],
    9: ["Naooo!!"],
    10: ["Naoooooooo!"],
    11: ["Entao e o chefao dessa vez?"],
    12: ["Ulala, atras de voce!"],
    13: ["Ulala, de novo atras de voce! Cuidado!"],
    14: ["Mais um atras de voce!"],
    15: ["Um escudo humano?"],
    16: ["Agora ele vai cantar! Mostra pra ele!"],
    17: ["Vai! Concentra a energia de danca de todos nessa",
         "antena e da o golpe final."],
    18: ["Mira na cabeca! Pega ele de um tiro so!"],
    19: ["Ulala,",
         "Cuidado"],
    20: [""],
    21: ["Ulala, agora depende tudo de voce!",
         "O destino da galaxia depende dos",
         "seus passos funky!"],
    22: [""],
    23: [""],
    24: ["Vou levar essa transmissora espacial",
         "como lembranca!"],
    25: ["Ah, sim, deixa eu te apresentar um amigo."],
    26: ["E agora, o que voce vai fazer?"],
    27: ["Ah, ah, ah. Hora de brincar!"],
    28: ["Se atirar normal, vai acertar o Presidente."],
    29: ["Olha,",
         "o poder da cantilena do Presidente!"],
    30: ["Vamos tocar!"],
    31: ["Ahh!"],
    32: ["Voce e muito mais forte do que eu pensava!",
         "Mas!"],
    33: ["Ahhhhhhhhhh!!",
         "Eh...Sim, beleza!"],
    34: ["Eu me diverti bastante."],
    35: [""],
    36: [""],
    37: [""],
    38: ["Vamos atirar!"],
})

# R44VOCAP_I.BIN (8 entries - Report 4 Part 4 voice)
tb("R44VOCAP_I.BIN", {
    0: ["A energia acabou!",
        "Ulala! So nos resta acumular",
        "energia com a danca!"],
    1: ["Vamos juntar energia!"],
    2: ["Isso! Estamos acumulando energia!"],
    3: ["Sinal de robo se aproximando!"],
    4: ["Voce conseguiu, Ulala! Estamos salvos!"],
    5: ["Mas Fuuuuse!"],
    6: ["Okay!"],
    7: ["Vamos atiraaar!"],
})

# R51VOCAP_I.BIN (22 entries - Report 5 Part 1 voice)
tb("R51VOCAP_I.BIN", {
    0: [""],
    1: ["O que foi?!"],
    2: ["Vamos dancar!"],
    3: [""],
    4: [""],
    5: ["...com a gente!!!"],
    6: ["Boa noite a todos!"],
    7: ["Ta vindo alguem!"],
    8: ["Ahh!"],
    9: ["Quem e voce?!"],
    10: ["Mas quem e voce?!"],
    11: [""],
    12: ["Robos! Muitos, muitos, muitos robos!"],
    13: ["Vamos atirar!"],
    14: ["Fiquem\u00a4"],
    15: [""],
    16: [""],
    17: ["A localizacao do Purge e o Presidente",
         "aponta nessa direcao."],
    18: [""],
    19: ["Estamos cercados!"],
    20: [""],
    21: ["A gente ouviu na transmissao da Pine,",
         "heh heh!"],
})

# R52VOCAP_I.BIN (40 entries - Report 5 Part 2 voice)
tb("R52VOCAP_I.BIN", {
    0: ["Fomos ainda mais fundo.",
        "Sera que Purge e o Presidente estao aqui?!"],
    1: [""],
    2: ["E uma batalha de bandas!"],
    3: ["Vamos tocar!"],
    4: ["Vamos atirar!!!!!!!!"],
    5: ["Jaguar...?!"],
    6: ["Fiquem com a gente!!!"],
    7: ["O verdadeiro e diferente de todos os outros!"],
    8: ["Hora de uma guitarrada!"],
    9: ["E agora o coro!"],
    10: ["Agora tudo junto!"],
    11: ["E ele! O lendario reporter.",
         "Oh, e ele quem salvou a vida da Ulala."],
    12: ["Voce nao vai a lugar nenhum"],
    13: ["Se voce nao aceita um nao como resposta."],
    14: ["E uma batalha de bandas!"],
    15: ["Vamos tocar!"],
    16: ["Nao acabou!"],
    17: ["Ainda nao terminei com voces!"],
    18: ["Falta muito ainda, acreditem!!"],
    19: ["Onde...estou...?"],
    20: [""],
    21: [""],
    22: [""],
    23: ["Ulala?"],
    24: ["Obrigado......"],
    25: [""],
    26: ["Purge esta usando as antenas...",
         "Que roubou das emissoras de TV",
         "do espaco...",
         "Pra construir uma terrivel",
         "\"Arma de musica balistica\"...",
         "Se nao nos apressarmos,",
         "toda a Via Lactea estara em perigo!"],
    27: [""],
    28: [""],
    29: [""],
    30: [""],
    31: [""],
    32: ["Acerte o verdadeiro com o raio",
         "do botao O!"],
    33: [""],
    34: ["Acerte os falsos com o raio",
         "do botao X!"],
    35: [""],
    36: [""],
    37: ["Quer ganhar mais tempo?"],
    38: ["Agora e tarde demais!"],
    39: ["Hora de brincar!",
         "Acha que vai adivinhar o verdadeiro?",
         "Ah, ah, ah, ah, ah."],
})

# R61VOCAP_I.BIN (51 entries - Report 6 Part 1 voice)
tb("R61VOCAP_I.BIN", {
    0: ["Boa noite a todos!",
        "Acabamos de chegar na base",
        "principal do Purge."],
    1: ["Purge!!!!!"],
    2: ["Nao vamos permitir!"],
    3: ["Vamos atirar!"],
    4: ["Purge!"],
    5: ["O que?"],
    6: ["Mmmmmmmm, vamos dancar!"],
    7: [""],
    8: [""],
    9: [""],
    10: [""],
    11: [""],
    12: [""],
    13: ["A energia de danca do povo\u00a4"],
    14: ["Oh nao! Aqui e um caos!"],
    15: ["Minha nossa!!"],
    16: ["Ulalaaaaaaa!"],
    17: ["Vamos atirar!"],
    18: ["Bem-vindos ao meu show de TV!"],
    19: ["A antena que voce me deu funciona perfeitamente!"],
    20: ["Em breve esta antena",
         "tera energia suficiente",
         "pra obrigar toda a galaxia a dancar!",
         "Ah, ah, ah."],
    21: ["Onde voce estava??"],
    22: ["Mmmmmmmm, vamos dancar!"],
    23: [""],
    24: [""],
    25: ["Chegou a hora do convidado especial!"],
    26: ["O Presidente Peace!"],
    27: ["Vamos! Dimensao Danca X!"],
    28: ["Ulala, eu precisava da sua energia de danca!",
         "Agora temos toda a energia que precisamos!"],
    29: ["Nao se importa se eu interromper seu",
         "showzinho, ne?",
         "Ah, ah, ah!"],
    30: ["Esses sao os fas que foram sequestrados!"],
    31: ["Purge!!"],
    32: ["Se a gente puder evitar!"],
    33: [""],
    34: ["Esse e o fim da linha!"],
    35: ["Cosaaaa!"],
    36: ["Entao ele ta sugando toda a energia!"],
    37: ["Purge!!"],
    38: ["Nao vamos permitir!"],
    39: [""],
    40: ["Vamos atirar!"],
    41: ["Ahiiiiiiiiiii!"],
    42: ["Purge!!"],
    43: ["Vamos impedir!"],
    44: ["Vamos atirar!"],
    45: ["Aiiiiaaahhh!!"],
    46: ["Purge!!"],
    47: ["Vamos impedir!"],
    48: ["Vamos atirar!"],
    49: [""],
    50: ["Mmmmmmmm, vamos dancar!"],
})

# R62VOCAP_I.BIN (72 entries - Report 6 Part 2 voice - Finale)
tb("R62VOCAP_I.BIN", {
    0: ["Ulala, o que voce ta fazendo?!"],
    1: ["Ei, ei."],
    2: ["Levanta e bate palmas!",
        "Bate palmas apertando o direcional",
        "pra baixo!"],
    3: ["Concentra a forca dos 86.429 fas.",
        "Numa so forca funky!"],
    4: ["Desculpa por ter assustado voces!"],
    5: ["Agora, mete bronca!"],
    6: ["Voce era a mais forte de toda a galaxia, garota!"],
    7: ["Siga a melodia e aperte o direcional pra baixo!"],
    8: ["Fuse?!?"],
    9: ["Yo"],
    10: ["Hah!"],
    11: ["Pow!"],
    12: ["Mas quando que eu perdi..."],
    13: ["uma batalha de danca!?!"],
    14: ["Vamos dancar!!"],
    15: ["Vamos la!"],
    16: ["Libertamos o Presidente!!"],
    17: ["Entendido!"],
    18: ["Vamos cantar!"],
    19: ["Vamos la, galera. Chegou a hora",
         "de pegar pesado!"],
    20: ["Fuse?!"],
    21: ["Entendido"],
    22: ["Purge!",
         "Ja chega da sua",
         "TV lixo!"],
    23: ["Prontos pra atirar!"],
    24: ["O plano maligno do Purge de fazer a galaxia",
         "dancar ate a loucura foi impedido.",
         "Agora,",
         "o futuro",
         "nos sorri."],
    25: ["Sou a Ulala",
         "Ao vivo junto com todos esses amigos!"],
    26: ["Voces estiveram na companhia do Space Channel 5!"],
    27: ["Okay galera, vamos ate os confins da galaxia!"],
    28: ["Okay galera,",
         "vamos aos cantos mais remotos da galaxia!"],
    29: ["Ohh, sinto muito!"],
    30: ["Pistola musical balistica, fogo em 3! 2! 1!"],
    31: ["Ehhh?!"],
    32: ["O que ta acontecendo?!?!",
         "Isso nao e o que diz o meu",
         "teleprompter!!"],
    33: [""],
    34: [""],
    35: [""],
    36: ["Meu grande plano!!"],
    37: [""],
    38: ["Agora dancem ate o ultimo suspiro!!"],
    39: ["Ate a proxima semana!!"],
    40: ["Eu nao vou esquecer disso!"],
    41: ["Ulala, obrigado!!"],
    42: ["Finalmente posso cantar!"],
    43: ["Ulala!"],
    44: [""],
    45: ["Vou curar essa sua cabeca doente!"],
    46: ["Ulala!"],
    47: ["Ulala!"],
    48: ["Vamos cantar!"],
    49: ["E voce que nao e feliz!"],
    50: ["Ulala!"],
    51: [""],
    52: ["Sem o amor, a forca nao pode",
         "mudar nada!"],
    53: [""],
    54: [""],
    55: [""],
    56: [""],
    57: [""],
    58: [""],
    59: [""],
    60: [""],
    61: [""],
    62: [""],
    63: [""],
    64: [""],
    65: [""],
    66: ["Vamos atirar!"],
    67: [""],
    68: [""],
    69: [""],
    70: ["Voces fizeram um otimo trabalho! Nao acredito",
         "que estamos todos sao e salvos!",
         "Foi por pouco! Quando eu cai,",
         "me vi em maus lencois e todos gritavam.",
         "Achei que nao ia conseguir!"],
    71: ["Voces fizeram um otimo trabalho! Nao acredito",
         "que estamos todos sao e salvos!",
         "Te assustei? Te assustei?",
         "Ah, qual e! Acha mesmo que matam gente",
         "num jogo como esse?",
         "Com certeza! Ah, ah, ah, ah!"],
})

# R62MUCAP_I.BIN (1 big entry + empties - Report 6 Music)
tb("R62MUCAP_I.BIN", {
    0: ["Aiaaaaahhhhh!!",
        "Agora, mete bronca!",
        "Fuse?!?",
        "Concentra a forca dos 86.429 fas.",
        "Numa so forca funky!",
        "Entendido",
        "Purge! Ja chega da sua",
        "TV lixo!",
        "Sem o amor, a forca",
        "nao podera mudar nada!",
        "Vou curar essa sua cabeca doente!",
        "E voce que nao e feliz!",
        "Vamos atirar!",
        "Ate a proxima semana!!",
        "O plano maligno do Purge de fazer",
        "a galaxia dancar ate a loucura foi impedido.",
        "Agora,",
        "o futuro",
        "nos sorri.",
        "Sou a Ulala",
        "Ao vivo junto com todos esses amigos!",
        "Voces estiveram na companhia do Space Channel 5!",
        "Voce era a mais forte de toda a galaxia, garota!"],
})

# MAKUCAP_I.BIN (11 entries - Opening/Cutscenes)
# Many entries have encoding issues (mixed languages in originals).
# We translate what we can.
tb("MAKUCAP_I.BIN", {
    0: [""],
    1: [""],
    2: [""],
    3: ["E isso o que??!",
        "Voces viram?",
        "Ehh?!?!",
        "Vai, Ulala!",
        "Entendido!",
        "Sou eu, Pudding!",
        "Nao desista!",
        "Hora de uma batalha de danca!",
        "Vamos dancar!",
        "Sao os reporters dos Piratas Espaciais",
        "Meu nome e",
        "Jaguar!",
        "Estamos aqui pra descobrir a verdade.",
        "Nao vou desistir!",
        "Salvamos Space Michael!",
        "Obrigado, Ulala!",
        "Ulala, voce mandou muito bem.",
        "Voce nao esta mais sozinha."],
    4: [""],
    5: [""],
    6: ["Vao, meus robos! Mostrem aos humanos",
        "como se danca!",
        "Tem umas criaturas estranhas dancando",
        "nessa area!",
        "Ulala, entra em acao!",
        "Entendido!",
        "Vamos, Ulala!",
        "Okay!",
        "Bom, meus queridos, vamos comecar!"],
    7: ["Senhoras e senhores, boa tarde!",
        "Presidente Peace, tem algo a declarar?",
        "Mas claro! Ehm...",
        "Ahhhhhhh!",
        "Hehe... seu querido",
        "Presidente Espacial Peace",
        "...agora pertence a nos, os Rhythm Rogues!"],
    8: ["Libertarei o Presidente e os refens em troca",
        "de um resgate de 6,6 trilhoes de dolares espaciais.",
        "Nos encontraremos no ponto Duplo-X!"],
    9: ["Para realizar meu grande plano, preciso",
        "desta transmissora espacial.",
        "Em breve, nenhum de voces tera motivo",
        "para se preocupar."],
    10: ["Agora, a verdadeira festa comeca!",
         "A galaxia inteira vai dancar pra mim!!"],
})

# ================================================================
# SAVE THE RESULT
# ================================================================
print(f"\nTotal translations applied: {count}")

with open(TRANSLATION_FILE, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Saved to {TRANSLATION_FILE}")

# Show stats
total_entries = 0
translated_entries = 0
for key, fdata in data["files"].items():
    for entry in fdata["entries"]:
        total_entries += 1
        if entry.get("translated"):
            translated_entries += 1
print(f"Coverage: {translated_entries}/{total_entries} entries have translations")
